[package]
name = "nearapps-contracts"
version = "0.1.0"
authors = ["Sebastian Gerske <13647606+H34D@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = {version = "4.0.0-pre.4", features = ["unstable"]}
# getrandom = { version = "0.2", features = ["js"] }

# crypto: ecdsa on secp256k1
[dependencies.secp256k1]
version = "0.20.3"
features = ["std", "recovery", "serde"]

# crypto: schnorr on ed25519
[dependencies.ed25519-dalek]
version = "1.0.1"

# hash: sha256
[dependencies.bitcoin_hashes]
version = "0.10.0"
features = ["std", "serde-std"]

# to de/serialize [u8; u64] arrays
[dependencies.serde-big-array]
version = "0.3.2"
features = ["const-generics"]

[dev-dependencies]
near-sdk-sim = "4.0.0-pre.4"

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true
