[build]
target = "wasm32-unknown-unknown"

[alias]
test-linux = "test --target=x86_64-unknown-linux-gnu"
test-apple = "test --target=x86_64-apple-darwin"
test-windows = "test --target=x86_64-pc-windows-msvc"


[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]

# rustflags = [
#     # strip
#     "-C", "link-arg=-s", 
#     # lto
#     "-C", "linker-plugin-lto",
#     "-C", "linker=clang",
#     "-C", "link-arg=-fuse-ld=lld"
#     ]

